using System;
using UnityEngine;
using Worldforge.Item;

namespace Worldforge.Crafting
{
    /// <summary>
    /// Represents an output item yield generated by a crafting recipe.
    /// Corresponds to Schema Part 5: RecipeOutput.
    /// </summary>
    [Serializable]
    public sealed class RecipeOutputEntry
    {
        [SerializeField] private ItemDefinition _item;
        [SerializeField, Min(1)] private int _amount = 1;
        [SerializeField, Range(0f, 1f)] private float _probability = 1.0f;

        public RecipeOutputEntry()
        {
            _amount = 1;
            _probability = 1.0f;
        }

        public RecipeOutputEntry(ItemDefinition item, int amount, float probability = 1.0f)
        {
            _item = item;
            _amount = Mathf.Max(1, amount);
            _probability = Mathf.Clamp01(probability);
        }

        public ItemDefinition Item
        {
            get { return _item; }
        }

        public int Amount
        {
            get { return _amount; }
        }

        public float Probability
        {
            get { return _probability; }
        }

        public void Validate()
        {
            _amount = Mathf.Max(1, _amount);
            _probability = Mathf.Clamp01(_probability);
        }
    }
}
